spring.application.name=Education-Center

spring.datasource.url=jdbc:postgresql://localhost:5432/education_center
spring.datasource.username=postgres
spring.datasource.password=le_mot_de_passe
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui/index.html

jwt.secret=q6R455BYJXKtonHuKIv8v9puLwnm1ECojpri6IGe1Ic=
jwt.expiration-ms=864000000
